[book]
title = "HAL Foundation"
description = "Documentation for the HAL management console (halOP & halOS)"
authors = ["Harald Pehl"]
language = "en"
src = "src"

[build]
build-dir = "book"

[output.html]
site-url = "/foundation/"
git-repository-url = "https://github.com/hal/foundation"
edit-url-template = "https://github.com/hal/foundation/edit/main/docs/src/{path}"
